name: smart_operation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.6.7
  connectivity_plus: ^6.1.4
  country_code_picker: ^3.0.0
  custom_date_range_picker: ^1.0.10
  dartz: ^0.10.1
  #  device_info: ^2.0.3
  device_info_plus: ^11.4.0
  dio: ^5.0.1
  dropdown_search: ^6.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  file_picker: ^10.1.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  fluid_dialog: ^2.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.1.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^5.1.1
  freezed_annotation: any
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  json_annotation: any
  loading_animation_widget: ^1.2.0+4
  dotted_border: ^2.1.0
  logger: ^2.5.0
  logging: ^1.1.1
  lottie: ^3.3.1
  material_dialogs: ^1.1.4
  country_picker: ^2.0.24
  convex_bottom_bar: ^3.2.0
  otp_text_field: ^1.1.3
  permission_handler: ^12.0.0+1
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  sentry_flutter: ^8.14.2
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  vibration: ^3.1.3
  webview_flutter: ^4.11.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any

build_runner:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/brandIcon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/brandIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/brandIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/brandIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/

  fonts:
    - family: default
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
